1. How to Creating a 3x3 Identity Matrix with Float Data Type?

In [1]:
import numpy as np
matrix = np.array([[1,2,4],[5,3,1],[2,7,4]])
print(matrix)

[[1 2 4]
 [5 3 1]
 [2 7 4]]


2. Create a 1D Array with Random Values between 0 and 1. 

In [9]:
import random
import numpy as np
arr1 = np.random.rand(5)
print(arr1)

[0.43313298 0.81108867 0.64531916 0.50081086 0.35788452]


3. Create a 2D Array with Random Integer Values. 

In [16]:
import random
import numpy as np
arr3 = np.random.randint(1, 100, (2, 4))
print(arr3)

[[59  7 18 90]
 [19 58 46 42]]
