In [1]:
import numpy as np

In [3]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [6]:
b = np.zeros([5, 2])
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [14]:
c = np.zeros([2, 4], dtype = float)
c
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
a1 = np.ones(6)
print(a1)

[1. 1. 1. 1. 1. 1.]


In [18]:
a5= np.ones([5,6], dtype = int)
print(a5)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [21]:
m = np.full(4, 'kya bolti public')
print(m)

['kya bolti public' 'kya bolti public' 'kya bolti public'
 'kya bolti public']


In [24]:
empty_space = np.empty(21)
print(empty_space)

[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.95820216e-306
 3.44902066e-307 1.60214553e-306 6.23054972e-307 1.20161797e-306
 6.23058707e-307 1.69120824e-306 8.45596650e-307 1.24611674e-306
 9.34602321e-307 1.69114441e-306 1.33511426e-306 1.78020848e-306
 8.01092457e-307 8.45593934e-307 9.34598246e-307 1.31565682e-312
 2.56761491e-312]


In [25]:
empty_space = np.empty(20)
print(empty_space)

[ 1.27319747e-313  3.39519327e-313  0.00000000e+000  1.39067116e-309
  8.82750252e-311  2.14321575e-311  1.69760311e-313  0.00000000e+000
  0.00000000e+000  0.00000000e+000  0.00000000e+000              nan
  6.84483060e-223 -6.11990857e-219  1.85674632e-314  1.17520759e-311
  0.00000000e+000  1.17525202e-311  1.17525202e-311  0.00000000e+000]


In [27]:
b = np.arange(0, 100, 5)
print(b)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [28]:
c = np.arange(20, 2, -3)
print(c)

[20 17 14 11  8  5]


In [30]:
a = np.linspace(0, 1, 12)
print(a)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


In [31]:
a = np.eye(12)
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [33]:
b = np.identity(12)
print(b)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [36]:
if 'a' == 'b':
    print("true")
else:
    print("false")

false


In [39]:
c = np.diag([1, 2, 3, "hello", "world"])
print(c)

[['1' '' '' '' '']
 ['' '2' '' '' '']
 ['' '' '3' '' '']
 ['' '' '' 'hello' '']
 ['' '' '' '' 'world']]


In [40]:
d = np.diag([4, 5], k = 2)
print(d)

[[0 0 4 0]
 [0 0 0 5]
 [0 0 0 0]
 [0 0 0 0]]


In [42]:
e = np.diag(c)
print(e)

['1' '2' '3' 'hello' 'world']


In [44]:
#find out all the necessary functions that are used in the numpy in the field of data analyst

In [45]:
import pandas as pd


In [46]:
s1 = pd.Series([12,34,2,32,33,542,3,452,2,1])
print(s1)

0     12
1     34
2      2
3     32
4     33
5    542
6      3
7    452
8      2
9      1
dtype: int64


In [47]:
s2 = pd.Series([100,200, 300], index = ['a', 'b', 'c'])
print(s2)

a    100
b    200
c    300
dtype: int64


In [57]:
s3 = pd.Series([{"name": "nevin"}, {"age": 31}])
print(s3)

0    {'name': 'nevin'}
1          {'age': 31}
dtype: object


In [58]:
s1

0     12
1     34
2      2
3     32
4     33
5    542
6      3
7    452
8      2
9      1
dtype: int64

In [59]:
s2

a    100
b    200
c    300
dtype: int64

In [60]:
s3

0    {'name': 'nevin'}
1          {'age': 31}
dtype: object

In [62]:
#arithmetic operation
s = pd.Series([1,223,234,0,1231,3,21,2])
print(s + 4)

0       5
1     227
2     238
3       4
4    1235
5       7
6      25
7       6
dtype: int64
