In [1]:
import numpy as np

In [9]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]], [[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [10]:
print(arr3.shape) # m x n of a matrix

(2, 3, 3)


In [11]:
print(arr3.size) # total number of elements

18


In [12]:
print(arr3.dtype) # to know the data types of the elements

int64


In [13]:
print(arr3.ndim) # to know the dimensions of the matrix

3


In [18]:
arr = np.arange(1,13)
arr
reshape = arr3.reshape(3, 2)

ValueError: cannot reshape array of size 18 into shape (3,2)