In [3]:
import numpy as np

In [4]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [5]:
a2 = np.zeros([5,2])
print(a2)


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [6]:
a3 = np.zeros([2,3], dtype=int)
print(a3)

[[0 0 0]
 [0 0 0]]


In [7]:
a4= np.ones(10)
print(a4)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [11]:
a5= np.ones([5,6], dtype = int)
print(a5)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [12]:
a5= np.ones([5,6], dtype = float)
print(a5)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [13]:
a5= np.ones([5,6], dtype = str)
print(a5)

[['1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1']]
