In [4]:
import numpy as np

In [15]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,4,3,2])
print(arr1 + arr2)
print("\n")
print(arr1 + arr2)
print("\n")
print(arr1 - arr2)
print("\n")
print(arr1 * arr2)
print("\n")
print(arr1 / arr2)

[6 6 6 6]


[6 6 6 6]


[-4 -2  0  2]


[5 8 9 8]


[0.2 0.5 1.  2. ]


In [16]:
a = [1,2,4]
b = [33,3,3]
c = a + b
print(c)

print(np.add(a, b))

[1, 2, 4, 33, 3, 3]
[34  5  7]


In [19]:
#arr1 = np.array([[1,2,3,4],[9,8,7,4]])
arr1 = np.array([1,2,3,4], dtype = float)
arr2 = np.array([[5,4,3,2],[1,54,3,2]])

print(arr1 + arr2)
print("\n")
print(arr1 + arr2)
print("\n")
print(arr1 - arr2)
print("\n")
print(arr1 * arr2)
print("\n")
print(arr1 / arr2)

[[ 6.  6.  6.  6.]
 [ 2. 56.  6.  6.]]


[[ 6.  6.  6.  6.]
 [ 2. 56.  6.  6.]]


[[ -4.  -2.   0.   2.]
 [  0. -52.   0.   2.]]


[[  5.   8.   9.   8.]
 [  1. 108.   9.   8.]]


[[0.2        0.5        1.         2.        ]
 [1.         0.03703704 1.         2.        ]]


In [23]:
arr12 = np.array([13,4,5,6,5,4,3,2])
print(arr12 < 6)
print(arr12[arr12 < 6])

[False  True  True False  True  True  True  True]
[4 5 5 4 3 2]


## indexing and slicing

In [27]:
sujal = np.array([12,3,2,1,2,3])

print(sujal[0])
print(sujal[-1])
print(sujal[2:])
print(sujal[3: 1: -1])

12
3
[2 1 2 3]
[1 2]


In [30]:
neel = np.array([[1,2,4,5],[2,65,4,6]])
print(neel[0, 1])    #position ke according hota hai. m x n . 
print("\n")
print(neel[1:, :2])

2


[[ 2 65]]
