In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,5,6])
print(arr)

[1 2 3 5 6]


In [4]:
print(np.__version__)

2.3.2


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


# dimentions

1. 0 D
2. 1 D
3. 2 D
4. 3 D

In [6]:
arr0 = np.array(123)
print(arr0)

123


In [11]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [12]:
print(arr1)

[1 2 3 4 5 6]


In [14]:
arr2 = np.array([[1,2,3], [3,1,2]])
print(arr2)

[[1 2 3]
 [3 1 2]]


In [15]:
arr2

array([[1, 2, 3],
       [3, 1, 2]])

In [18]:
arr3 = np.array([[[1,2,3,4], [4,3,2,1]],[[0,9,8,7],[6,7,8,9]]])
print(arr3)

[[[1 2 3 4]
  [4 3 2 1]]

 [[0 9 8 7]
  [6 7 8 9]]]


In [20]:
print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


In [24]:
arr5 = np.array([1,2,3,5,6,5,3,32], ndmin = 5)
print(arr5)
print(arr5.ndim)

[[[[[ 1  2  3  5  6  5  3 32]]]]]
5


In [30]:
arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[1])
print(arr[1] + arr[-1])

1
2
6


In [49]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr[1, 1, 0])

7


In [8]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:6:2])
print(arr[::2])

[1 2 3 4]
[5 6]
[2 4 6]
[1 3 5 7]


In [16]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:3])
print(arr[0:5, 4])

[7 8]
[ 5 10]
