In [1]:
import numpy as np

1. 3D array of shape (2,3,4) filled with integers 1–24


In [5]:
arr1 = np.arange(1, 25).reshape(2, 3, 4)
print(arr1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


2. 5×5 array with random integers 10–50, extract evens

In [32]:
arr2 = np.random.randint(10, 51, (5, 5))
evens = arr2[arr2 % 2 == 0]
print(arr2)
print()
print(evens)

[[42 39 40 18 11]
 [22 14 36 40 20]
 [49 38 13 10 15]
 [37 22 12 11 32]
 [25 45 24 26 34]]

[42 40 18 22 14 36 40 20 38 10 22 12 32 24 26 34]


3. Create two arrays a = np.arange(1,13).reshape(3,4) and b = np.array([10,20,30,40]). Use broadcasting to add b to every row of a.

In [10]:
a = np.arange(1, 13).reshape(3, 4)
b = np.array([10, 20, 30, 40])
res3 = a + b
print(res3)

[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]


4. Construct a 6×6 identity matrix and replace its secondary diagonal (from top-right to bottom-left) with all 7’s.

In [11]:
arr4 = np.eye(6, dtype=int)
print(arr4)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [12]:
arr4[np.arange(6), np.arange(5, -1, -1)] = 7
print(arr4)

[[1 0 0 0 0 7]
 [0 1 0 0 7 0]
 [0 0 1 7 0 0]
 [0 0 7 1 0 0]
 [0 7 0 0 1 0]
 [7 0 0 0 0 1]]


5. Generate 20 linearly spaced numbers between -5 and 5. Reshape into a (4,5) array and extract only the elements greater than 0.


In [14]:
arr5 = np.linspace(-5, 5, 20).reshape(4, 5)
greater_than_zero = arr5[arr5 > 0]
print(arr5)
print()
print(greater_than_zero)

[[-5.         -4.47368421 -3.94736842 -3.42105263 -2.89473684]
 [-2.36842105 -1.84210526 -1.31578947 -0.78947368 -0.26315789]
 [ 0.26315789  0.78947368  1.31578947  1.84210526  2.36842105]
 [ 2.89473684  3.42105263  3.94736842  4.47368421  5.        ]]

[0.26315789 0.78947368 1.31578947 1.84210526 2.36842105 2.89473684
 3.42105263 3.94736842 4.47368421 5.        ]


6. Create a 4×4 array with numbers from 1 to 16. Swap the first and last rows using slicing.


In [15]:
arr6 = np.arange(1, 17).reshape(4, 4)
print(arr6)
print()
arr6[[0, -1]] = arr6[[-1, 0]]
print((arr6))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[13 14 15 16]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


7. 
Create a 10×10 array with random floats between 0 and 1, then find the row with the maximum sum.


In [16]:
arr7 = np.random.rand(10, 10)
print(arr7)
print()
row_max_sum = arr7[np.argmax(arr7.sum(axis=1))]
print(row_max_sum)

[[0.24989487 0.9900581  0.49616536 0.81614814 0.830473   0.63015041
  0.12012014 0.93127386 0.13342945 0.99850471]
 [0.4358403  0.75019843 0.6173592  0.79062069 0.67630786 0.82534515
  0.32518127 0.54401554 0.99540931 0.70848827]
 [0.17756978 0.0579399  0.39919484 0.78946488 0.98853851 0.64003254
  0.97658141 0.34910191 0.45037029 0.47857296]
 [0.67146497 0.98634707 0.83504734 0.63147371 0.93754545 0.79780478
  0.79165602 0.26807742 0.39628054 0.80549995]
 [0.86692276 0.24137814 0.32605183 0.67998248 0.22121048 0.21237763
  0.63663718 0.82020056 0.08057457 0.13619492]
 [0.82899936 0.71181475 0.81563531 0.75981653 0.25287019 0.83359323
  0.61734768 0.41828487 0.96361455 0.97473686]
 [0.58609046 0.83261261 0.2962663  0.37205035 0.79453948 0.84858694
  0.2287376  0.02849627 0.63246264 0.88968223]
 [0.65701908 0.5868446  0.94890588 0.29356722 0.95615259 0.64802752
  0.68970581 0.14307045 0.0343604  0.87926797]
 [0.39455901 0.17985711 0.23164421 0.55219271 0.3331624  0.96644842
  0.58492583

8. Given arr = np.arange(1,26).reshape(5,5), extract the submatrix of even numbers only, keeping their 2D structure.


In [33]:
arr = np.arange(1, 26).reshape(5, 5)
mask = arr % 2 == 0
submatrix = np.where(mask, arr, 0)
print(submatrix)

[[ 0  2  0  4  0]
 [ 6  0  8  0 10]
 [ 0 12  0 14  0]
 [16  0 18  0 20]
 [ 0 22  0 24  0]]


9. Generate two arrays a = np.array([1,2,3]) and b = np.array([[10],[20],[30]]). Perform multiplication using broadcasting and explain the result.


In [20]:
a9 = np.array([1, 2, 3])
b9 = np.array([[10], [20], [30]])
res9 = a9 * b9

print(a9)
print()
print(b9)
print()
print(res9)

[1 2 3]

[[10]
 [20]
 [30]]

[[10 20 30]
 [20 40 60]
 [30 60 90]]


10. Create a diagonal matrix with values [5,10,15,20]. Then convert it into a full 4×4 matrix where diagonal values remain but others are filled with -1.


In [21]:
diag_vals = [5, 10, 15, 20]
arr10 = np.full((4, 4), -1)
np.fill_diagonal(arr10, diag_vals)

print(diag_vals)
print()
print(arr10)

[5, 10, 15, 20]

[[ 5 -1 -1 -1]
 [-1 10 -1 -1]
 [-1 -1 15 -1]
 [-1 -1 -1 20]]


11. Using np.eye(5), create a 5×5 matrix with diagonal values equal to multiples of 3.


In [22]:
arr11 = np.eye(5) * np.arange(1, 6) * 3
print(arr11)

[[ 3.  0.  0.  0.  0.]
 [ 0.  6.  0.  0.  0.]
 [ 0.  0.  9.  0.  0.]
 [ 0.  0.  0. 12.  0.]
 [ 0.  0.  0.  0. 15.]]


12. Construct an array of shape (3,4,2) with values from 1 to 24. Flatten it using ravel(), and then reshape it into (2,3,4).


In [23]:
arr12 = np.arange(1, 25).reshape(3, 4, 2)
flattened = arr12.ravel()
reshaped12 = flattened.reshape(2, 3, 4)
print(arr12)
print()
print(flattened)
print()
print(reshaped12)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


13. Generate a 7×7 matrix of random integers (1–100). Replace all values divisible by 5 with -5 using boolean indexing.


In [27]:
arr13 = np.random.randint(1, 101, (7, 7))
arr13[arr13 % 5 == 0] = -5
print(arr13)

[[62 21  2 -5 28 49 32]
 [-5 -5  4 23 14 22 -5]
 [18 98 56 57 37 33 43]
 [38 99  2  3 84 91 62]
 [57 28 86 57 -5 89 -5]
 [47 -5 73 44 -5 12 82]
 [49 23 97 26 67 39 81]]


14. Given arr = np.linspace(0, 2*np.pi, 10), compute sine and cosine values for each element and stack them into a 2D array with shape (10,2).


In [28]:
arr14 = np.linspace(0, 2*np.pi, 10)
sin_cos = np.column_stack((np.sin(arr14), np.cos(arr14)))
print(arr14)
print()
print(sin_cos)

[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]

[[ 0.00000000e+00  1.00000000e+00]
 [ 6.42787610e-01  7.66044443e-01]
 [ 9.84807753e-01  1.73648178e-01]
 [ 8.66025404e-01 -5.00000000e-01]
 [ 3.42020143e-01 -9.39692621e-01]
 [-3.42020143e-01 -9.39692621e-01]
 [-8.66025404e-01 -5.00000000e-01]
 [-9.84807753e-01  1.73648178e-01]
 [-6.42787610e-01  7.66044443e-01]
 [-2.44929360e-16  1.00000000e+00]]


15. Create a 5×5 checkerboard pattern (alternating 0s and 1s) using slicing, without manually typing each element.

In [30]:
arr15 = np.zeros((5, 5), dtype=int)
arr15[::2, 1::2] = 1
arr15[1::2, ::2] = 1
arr15
print(arr15)

[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]
